services:
  db:
    # container name can be something else
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: suryapradipta
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

